# This workflow will build and upload the Frontend (Vue.js App) an Amazon S3 bucket.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

# on:
#     release:
#       types: [created]
      
on:
  push:
    branches: master
  
name: Deploy API Documentation to an Amazon S3 Bucket

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Install
      run: npm install

    - name: Build
      run: npm run-script generate

    # Upload the pre-built static content to S3 bucket
    - name: Deploy to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --recursive \
        --region ap-southeast-1 \
        public s3://${{ secrets.AWS_S3_BUCKET_DOCS_DEV }}